[package]
name = "maafw-sys"
version = "0.1.0"
edition = "2021"
description = "Low-level MAAFramework bindings for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
